config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :words
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if params[:answer]
      word_by_answer
    else
      @word = Word.find(Word.pluck(:id).sample).send(translate_version) if words_length != 0
    end
  end

  private

  def words_length
    @words_length ||= Word.count
  end

  def translate_version
    rand(0..1) == 0 ? 'english' : 'ukraine'
  end

  def word_by_answer
    @word = Word.find_by(english: params[:answer]).try(:ukraine)
    @word = Word.find_by(ukraine: params[:answer]).english unless @word
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    Word.create(word_params)
    redirect_to words_path
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    word = Word.find(params[:id])
    word.update(word_params)
  end

  def destroy
    word = Word.find(params[:id])
    word.destroy
    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit!
  end
end

app/views/dashboard/index.html.slim
.row.text-center
  .large-5.medium-8.small-8.columns.large-offset-3.medium-offset-2.small-offset-2
    h1.subheader= @word
.row.text-center
  .large-5.medium-10.small-10.columns.large-offset-3.medium-offset-1.small-offset-1
    = link_to 'Answer', root_path(answer: @word), class: :button
    =< link_to 'Next word', root_path, class: :button

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Words</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='sub-nav'>
      <dd><%= link_to 'Home', root_path %></dd>
      <dd><%= link_to 'Words', words_path %></dd>
    </div>
    <%= yield %>

  </body>
</html>

app/views/words/_form.html.slim
= simple_form_for @word do |f|
  = f.input :english
  = f.input :ukraine
  = f.button :submit

app/views/words/index.html.slim
.row
  .columns.large-4.large-offset-4
    table.hover
      thead
        tr
          th ID
          th English
          th Ukraine
      tbody
        - @words.each do |word|
          tr
            td= word.id
            td= word.english
            td= word.ukraine
  .columns.large-2
    = link_to 'New word', new_word_path, class: :button

app/views/words/new.html.slim
= render 'form'